// Generated from dalfilo_adv_pipeline_ss26.xlsx, sheet ADV Pipeline.
window.DALFILO_SEED_ASSETS = [
  {
    "id": "asset-1",
    "campaign": "Festa della Mamma — Free Embroidery Phase 1",
    "goLive": "22/04",
    "deadline": "17/04/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Free embroidery — UGC unboxing video",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Percale",
    "productCluster": "",
    "hook": "Personal / emotional reveal of embroidery gift. Show stitching in first 2s.",
    "funnel": "pr_ + rm_",
    "landing": "plp",
    "naming": "pr_it_bed_video_ugc_mamma26_unboxing_v1_plp",
    "assignee": "Federica",
    "status": "Done",
    "rationale": "Unboxing DCA CPR €2.42–€2.82 in Q1 — highest-efficiency gifting format.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-2",
    "campaign": "Festa della Mamma — Free Embroidery Phase 1",
    "goLive": "22/04",
    "deadline": "17/04/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Free embroidery — carousel gift ideas",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Slide 1: 'Regala qualità, ricama amore'. Each slide: product + price + embroidery detail.",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bed_carousel_brand_mamma26_giftideas_v1_hp",
    "assignee": "Federica",
    "status": "Done",
    "rationale": "Carousel HP CPR €7.71 in Q1. Gift ideas carousel performed well last year per Egle.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-3",
    "campaign": "Festa della Mamma — Free Embroidery Phase 1",
    "goLive": "22/04",
    "deadline": "17/04/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Free embroidery — static v1 (embroidery close-up)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Extreme close-up on stitching thread. Warm, tactile feel. No logo overlay.",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_mamma26_product_v1_hp",
    "assignee": "Federica",
    "status": "Done",
    "rationale": "Static is the volume driver — 9,709 results in Q1. Always run 2 variants.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-4",
    "campaign": "Festa della Mamma — Free Embroidery Phase 1",
    "goLive": "22/04",
    "deadline": "17/04/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Free embroidery — static v2 (full product)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Full product in warm setting. Gift ribbon. 'Ricamo gratuito' copy prominent.",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_mamma26_product_v2_hp",
    "assignee": "Federica",
    "status": "Done",
    "rationale": "Second static variant — gives algorithm options, reduces creative fatigue.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-5",
    "campaign": "Festa della Mamma — Free Embroidery Phase 1",
    "goLive": "22/04",
    "deadline": "17/04/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "FOMO GIF — countdown / urgency loop",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Animated: 'Ultimi giorni per garantire consegna' loop. 2–3 sec, no sound.",
    "funnel": "rt_",
    "landing": "pdp",
    "naming": "rt_it_bed_gif_brand_mamma26_urgency_v1_pdp",
    "assignee": "Federica",
    "status": "Done",
    "rationale": "GIF CPM €6.30–€7.06 — cheapest format. Mandatory FOMO asset for retargeting.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-6",
    "campaign": "Festa della Mamma — Free Embroidery Phase 1",
    "goLive": "22/04",
    "deadline": "17/04/2026",
    "country": "ITA + DACH",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "assetName": "Pre-embroidered products — static (ready to ship)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "'Già ricamato, pronto per la consegna'. Show finished product + gift wrap.",
    "funnel": "rm_",
    "landing": "pdp",
    "naming": "rm_it_bed_static_brand_mamma26_preembroidered_v1_pdp",
    "assignee": "Federica",
    "status": "Done",
    "rationale": "Conversion fallback when delivery deadline passes. Separate asset needed.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-7",
    "campaign": "Festa della Mamma — Free Embroidery Phase 1",
    "goLive": "22/04",
    "deadline": "17/04/2026",
    "country": "ITA + DACH",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "assetName": "UGC+AI — urgency voiceover variant",
    "format": "Video",
    "creativeType": "UGC+AI",
    "productCategory": "",
    "productCluster": "",
    "hook": "Same clip as UGC v1. Add AI voiceover: urgency tone, gifting emotional angle.",
    "funnel": "pr_",
    "landing": "pdp",
    "naming": "pr_it_bed_video_ai_mamma26_urgency_v1_pdp",
    "assignee": "Federica",
    "status": "Done",
    "rationale": "Apr test: urgency+ASMR AI variant CPR €5.97 on 23 results — best AI format.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-8",
    "campaign": "Mamma — FOMO Final Push (delivery deadline)",
    "goLive": "04/05",
    "deadline": "09/05",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "FOMO countdown GIF v2 — delivery deadline",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Animated: 'Ordina entro il [DATE] — consegna garantita'. Update date dynamically.",
    "funnel": "rt_",
    "landing": "pdp",
    "naming": "rt_it_bed_gif_brand_mamma26_fomo_v2_pdp",
    "assignee": "Federica",
    "status": "Done",
    "rationale": "FOMO GIF is the retargeting urgency weapon — lowest CPM, highest frequency tolerance.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-9",
    "campaign": "Mamma — FOMO Final Push (delivery deadline)",
    "goLive": "04/05",
    "deadline": "09/05",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Static — no embroidery final phase",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "'Non garantiamo più la consegna con ricamo — ma il regalo è comunque perfetto.'",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_mamma26_noembroidery_v1_hp",
    "assignee": "Federica",
    "status": "Done",
    "rationale": "Egle confirmed: separate asset for when embroidery delivery is no longer guaranteed.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-10",
    "campaign": "Mamma — FOMO Final Push (delivery deadline)",
    "goLive": "04/05",
    "deadline": "09/05",
    "country": "ITA + DACH",
    "priority": "Medium",
    "campaignType": "Sale / Push",
    "assetName": "Bed + bath bundle carousel — final push",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Gift set combos: 'Letto + bagno, il regalo doppio'. Price visible each slide.",
    "funnel": "rt_",
    "landing": "hp",
    "naming": "rt_it_mixed_carousel_brand_mamma26_bundle_v1_hp",
    "assignee": "Federica",
    "status": "Done",
    "rationale": "Cross-sell: bath+bed bundle dramatically increases AOV. Strong on warm audience.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-11",
    "campaign": "Dalfilo Days - Phase 1",
    "goLive": "21/05/2026",
    "deadline": "15/05/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Dalfilo Days — UGC hero video (beds)",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Percale",
    "productCluster": "",
    "hook": "Product reveal + 'Dal Filo Days'  + Free Embroidery",
    "funnel": "pr_ + rm_",
    "landing": "pdp",
    "naming": "pr_it_bed_video_ugc_dfdays26_product_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Same logic as WS: UGC + offer = highest conversion efficiency. Scale this first.",
    "storytelling": "prospecting:\n- Tornano i Dalfilo Days: celebra l’artigianato e rinnova la tua casa.\n- Dalfilo Days: il momento perfetto per scoprire il comfort dei tessuti fatti a mano.\n- Tessuti freschi e artigianali: prepara la tua casa alla nuova stagione con Dalfilo.\n- Dalfilo Days: la leggerezza del Percalle per il tuo benessere quotidiano.\n- La casa si alleggerisce: scopri l’artigianato italiano con i Dalfilo Days.\n - Approfitta dei Dalfilo Days!\n\nremarketing:\n- Dalfilo Days: celebriamo l'artigianato con un -20% dedicato a te.\n- Celebra i nostri artigiani e porta a casa l'eccellenza con il -20%.\n- Dalfilo Days: la qualità che dura nel tempo, oggi al -20% per il tuo cambio stagione.\n- Preparati per il cambio stagione: Da oggi e per pochi giorni, i più amati al -20%!\n - Approfitta dei Dalfilo Days!\n- Dalfilo Days: la nostra festa per celebrare il lavoro dei nostri artigiani e il supporto dei nostri clienti!\n- Regalati il piacere di sognare Made in Italy",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-12",
    "campaign": "Dalfilo Days - Phase 1",
    "goLive": "21/05/2026",
    "deadline": "15/05/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Dalfilo Days — static offer v1 (abbraccio cuscini)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "",
    "hook": "Product + % offer prominent on HP. Strong sale framing.",
    "funnel": "pr_ + rm_",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_dfdays26_offer_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "WS static rm_ CPR €3.26–€5.09 — the conversion workhorse of every sale period.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-13",
    "campaign": "Dalfilo Days - Phase 1",
    "goLive": "21/05/2026",
    "deadline": "15/05/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Dalfilo Days — static offer v2 (embroidery focus)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "",
    "hook": "'Personalizza il tuo ordine — ricamo gratuito'. Embroidery as differentiator.",
    "funnel": "pr_ + rm_",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_dfdays26_offer_v2_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Free embroidery is the key offer lever. Always needs a dedicated static.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-14",
    "campaign": "Dalfilo Days - Phase 1",
    "goLive": "21/05/2026",
    "deadline": "15/05/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Dalfilo Days — timer GIF urgency free embroidery",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Mix Letto + Bagno",
    "productCluster": "",
    "hook": "Animated: product + price + free embroidery (last hours)",
    "funnel": "rt_",
    "landing": "pdp",
    "naming": "rt_it_bed_gif_brand_dfdays26_urgency_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "GIF = cheapest CPM in account. Mandatory for every sale period retargeting layer.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-15",
    "campaign": "Dalfilo Days - Phase 1",
    "goLive": "21/05/2026",
    "deadline": "15/05/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Dalfilo Days — carousel always on",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "",
    "hook": "\"Celebra gli artigiani con i Dalfilo Days\"",
    "funnel": "pr_",
    "landing": "hp",
    "naming": "pr_it_bed_carousel_brand_dfdays26_bestseller_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Carousel rm_ HP CPR €6.02 in Q1 WS. Good discovery layer alongside statics.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-16",
    "campaign": "Dalfilo Days - Phase 1",
    "goLive": "21/05/2026",
    "deadline": "15/05/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Dalfilo Days — carousel novità",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "",
    "hook": "\"Celebra l'artigianato italiano con i Dalfilo Days\"",
    "funnel": "pr_",
    "landing": "hp",
    "naming": "pr_it_bed_carousel_brand_dfdays26_bestseller_v2_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Carousel rm_ HP CPR €6.02 in Q1 WS. Good discovery layer alongside statics.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-17",
    "campaign": "Dalfilo Days - Phase 1",
    "goLive": "21/05/2026",
    "deadline": "15/05/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Dalfilo Days — carousel always on",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Mix Letto + Bagno",
    "productCluster": "",
    "hook": "\"Essenziali Dalfilo tutti al -20%\"",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bed_carousel_brand_dfdays26_bestseller_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Carousel rm_ HP CPR €6.02 in Q1 WS. Good discovery layer alongside statics.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-18",
    "campaign": "Dalfilo Days - Phase 1",
    "goLive": "21/05/2026",
    "deadline": "15/05/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Dalfilo Days — carousel novità",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Mix Letto + Bagno",
    "productCluster": "",
    "hook": "\"Novità Dalfilo tutte al -20%\"",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bed_carousel_brand_dfdays26_bestseller_v2_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Carousel rm_ HP CPR €6.02 in Q1 WS. Good discovery layer alongside statics.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-19",
    "campaign": "Dalfilo Days - Phase 2",
    "goLive": "21/05/2026",
    "deadline": "15/05/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Dalfilo Days — UGC hero video (beds)",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Percale",
    "productCluster": "",
    "hook": "Product reveal + 'Dalfilo Days'",
    "funnel": "pr_ + rm_",
    "landing": "pdp",
    "naming": "pr_it_bed_video_ugc_dfdays26_product_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Same logic as WS: UGC + offer = highest conversion efficiency. Scale this first.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-20",
    "campaign": "Dalfilo Days - Phase 2",
    "goLive": "21/05/2026",
    "deadline": "15/05/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Dalfilo Days — static offer (free shipping focus)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Mix Letto",
    "productCluster": "",
    "hook": "Product + % offer prominent on HP. Strong sale framing.",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_dfdays26_offer_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "WS static rm_ CPR €3.26–€5.09 — the conversion workhorse of every sale period.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-21",
    "campaign": "Dalfilo Days - Phase 2",
    "goLive": "21/05/2026",
    "deadline": "15/05/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Dalfilo Days — timer GIF urgency last days free shipping",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Mix Letto",
    "productCluster": "",
    "hook": "Animated: product + price reveal loop. 'Solo per oggi' or countdown.",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_dfdays26_offer_v2_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Free embroidery is the key offer lever. Always needs a dedicated static.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-22",
    "campaign": "Dalfilo Days - Phase 2",
    "goLive": "21/05/2026",
    "deadline": "15/05/2026",
    "country": "ITA + DACH",
    "priority": "High",
    "campaignType": "Sale / Push",
    "assetName": "Dalfilo Days — timer GIF urgency last hours",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percale",
    "productCluster": "",
    "hook": "Animated: product + price reveal loop. 'Solo per oggi' or countdown.",
    "funnel": "rm_",
    "landing": "pdp",
    "naming": "rt_it_bed_gif_brand_dfdays26_urgency_v1_pdp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "GIF = cheapest CPM in account. Mandatory for every sale period retargeting layer.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-23",
    "campaign": "Kids Collection Launch — Bed + Bath",
    "goLive": "14/05/2026",
    "deadline": "12/05/2026",
    "country": "ITA + DACH",
    "priority": "Medium",
    "campaignType": "Product Launch",
    "assetName": "Kids bed — UGC video (child using product)",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Mix Letto",
    "productCluster": "",
    "hook": "TBD",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "pr_it_bed_video_ugc_kids26_lifestyle_v1_hp",
    "assignee": "Federica",
    "status": "Work in progress",
    "rationale": "Kids products need emotion/lifestyle UGC. Authenticity is the hook.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-24",
    "campaign": "Kids Collection Launch — Bed + Bath",
    "goLive": "14/05/2026",
    "deadline": "12/05/2026",
    "country": "ITA + DACH",
    "priority": "Medium",
    "campaignType": "Product Launch",
    "assetName": "Kids bath — UGC+AI voiceover (warmth angle)",
    "format": "Video",
    "creativeType": "UGC+AI",
    "productCategory": "Mix Bagno",
    "productCluster": "",
    "hook": "TBD",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "pr_it_bath_video_ai_kids26_lifestyle_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "A/B test vs UGC without voice. Apr AI standard variant VR 16.5% beats brand 14.4%.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-25",
    "campaign": "Kids Collection Launch — Bed + Bath",
    "goLive": "14/05/2026",
    "deadline": "12/05/2026",
    "country": "ITA + DACH",
    "priority": "Medium",
    "campaignType": "Product Launch",
    "assetName": "Kids bed — carousel",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Mix Letto",
    "productCluster": "",
    "hook": "Culla + lettino + piazza singola",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_kids26_product_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Static is the volume anchor. Always 2 variants minimum for algorithm.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-26",
    "campaign": "Kids Collection Launch — Bed + Bath",
    "goLive": "14/05/2026",
    "deadline": "12/05/2026",
    "country": "ITA + DACH",
    "priority": "Medium",
    "campaignType": "Product Launch",
    "assetName": "Kids bath — carousel",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Mix Bagno",
    "productCluster": "",
    "hook": "Poncho + mini bathrobe",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_kids26_product_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Static is the volume anchor. Always 2 variants minimum for algorithm.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-27",
    "campaign": "Kids Collection Launch — Bed + Bath",
    "goLive": "14/05/2026",
    "deadline": "12/05/2026",
    "country": "ITA + DACH",
    "priority": "Medium",
    "campaignType": "Product Launch",
    "assetName": "Kids bath — GIF colour reveal loop",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Mix Bagno",
    "productCluster": "",
    "hook": "Animated loop: 3 colours rotating (ciliegio / salvia / bianco). No text needed.",
    "funnel": "rm_",
    "landing": "pdp",
    "naming": "rt_it_bath_gif_brand_kids26_product_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "GIF on new collection: Eden preorder VR 18.8% at CPM €6.29. Colour variety = GIF strength.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-28",
    "campaign": "Kids Collection Launch — Bed + Bath",
    "goLive": "14/05/2026",
    "deadline": "12/05/2026",
    "country": "ITA + DACH",
    "priority": "Medium",
    "campaignType": "Product Launch",
    "assetName": "Kids — carousel full range",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Mix Letto + Bagno",
    "productCluster": "",
    "hook": "Poncho → mini bathrobe → bed linen",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_mixed_carousel_brand_kids26_range_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Range carousel for discovery. Lets audience see full kids offering in one ad.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-29",
    "campaign": "Beach Collection — Portofino Beach Towels",
    "goLive": "25/05/2026",
    "deadline": "22/05/2026",
    "country": "",
    "priority": "Low",
    "campaignType": "Product Launch",
    "assetName": "Beach towels — UGC video (outdoor, movement)",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "",
    "productCluster": "",
    "hook": "First 2s: beach/outdoor movement. Texture + colour vibrancy in natural light. No studio.",
    "funnel": "pr_",
    "landing": "hp",
    "naming": "pr_it_bath_video_ugc_ss26beach_lifestyle_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Outdoor products need lifestyle UGC — same logic as Sport Collection (CPR €2.70 at launch).",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-30",
    "campaign": "Beach Collection — Portofino Beach Towels",
    "goLive": "25/05/2026",
    "deadline": "22/05/2026",
    "country": "",
    "priority": "Low",
    "campaignType": "Product Launch",
    "assetName": "Beach towels — static v1 (context) + v2 (texture)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "v1: Portofino/sea context lifestyle. v2: product texture close-up with colour names.",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bath_static_brand_ss26beach_lifestyle_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Summer product static must show context — beach, light, colour. Not white background.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-31",
    "campaign": "Beach Collection — Portofino Beach Towels",
    "goLive": "25/05/2026",
    "deadline": "22/05/2026",
    "country": "",
    "priority": "Low",
    "campaignType": "Product Launch",
    "assetName": "Beach towels — GIF texture loop",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Fabric in sea breeze / slow motion wave effect. Loop 2–3s.",
    "funnel": "rt_",
    "landing": "pdp",
    "naming": "rt_it_bath_gif_brand_ss26beach_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "GIF mandatory on every launch. One per collection = Andromeda format diversity + lowest CPM.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-32",
    "campaign": "Sport Collection — Super Push",
    "goLive": "19/05",
    "deadline": "15/05",
    "country": "",
    "priority": "High",
    "campaignType": "Product Launch",
    "assetName": "Sport — UGC video (movement hook)",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "",
    "productCluster": "",
    "hook": "First 2s: physical movement (gym, morning, travel). First-person POV. Real use.",
    "funnel": "pr_",
    "landing": "hp",
    "naming": "pr_it_bath_video_ugc_ss26sport_lifestyle_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Action item A3 from Q1. Sport static rt_ CPR €2.70 — audience warm. UGC is the missing layer.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-33",
    "campaign": "Sport Collection — Super Push",
    "goLive": "19/05",
    "deadline": "15/05",
    "country": "",
    "priority": "Medium",
    "campaignType": "Product Launch",
    "assetName": "Sport — UGC+AI voiceover (performance angle)",
    "format": "Video",
    "creativeType": "UGC+AI",
    "productCategory": "",
    "productCluster": "",
    "hook": "Same clip as v1. AI voice: 'Qualità per chi si allena'. Performance/quality angle.",
    "funnel": "pr_",
    "landing": "hp",
    "naming": "pr_it_bath_video_ai_ss26sport_lifestyle_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "A/B test vs UGC without voice. Continue testing on Sport after Botanica learnings.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-34",
    "campaign": "Sport Collection — Super Push",
    "goLive": "19/05",
    "deadline": "15/05",
    "country": "",
    "priority": "High",
    "campaignType": "Product Launch",
    "assetName": "Sport — GIF retargeting",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Product in motion. Short loop. No text — let the product speak.",
    "funnel": "rt_",
    "landing": "pdp",
    "naming": "rt_it_bath_gif_brand_ss26sport_product_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Sport has no GIF yet. rt_ Sport static CPR €2.70 proves warm audience — GIF captures it cheaper.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-35",
    "campaign": "Summer Sale — PEAK VOLUME",
    "goLive": "01/06",
    "deadline": "25/05",
    "country": "",
    "priority": "High",
    "campaignType": "Peak Volume",
    "assetName": "Summer Sale — UGC hero v1 (beds)",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "",
    "productCluster": "",
    "hook": "Summer morning, linen in natural light. Offer in overlay text. First 2s: texture + warmth.",
    "funnel": "pr_",
    "landing": "hp",
    "naming": "pr_it_bed_video_ugc_ss26sale_lifestyle_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "WS essenziali UGC video VR 39.8%, CPR €5.10 — 2nd best video of Q1. Replicate.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-36",
    "campaign": "Summer Sale — PEAK VOLUME",
    "goLive": "01/06",
    "deadline": "25/05",
    "country": "",
    "priority": "High",
    "campaignType": "Peak Volume",
    "assetName": "Summer Sale — UGC hero v2 (bath)",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "",
    "productCluster": "",
    "hook": "Bath products in summer: pool, garden, morning routine. Cross-sell potential.",
    "funnel": "pr_",
    "landing": "hp",
    "naming": "pr_it_bath_video_ugc_ss26sale_lifestyle_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Two UGC videos (bed+bath) gives algorithm two distinct audiences — doubles prospecting surface.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-37",
    "campaign": "Summer Sale — PEAK VOLUME",
    "goLive": "01/06",
    "deadline": "25/05",
    "country": "",
    "priority": "High",
    "campaignType": "Peak Volume",
    "assetName": "Summer Sale — UGC+AI urgency v1",
    "format": "Video",
    "creativeType": "UGC+AI",
    "productCategory": "",
    "productCluster": "",
    "hook": "Urgency voiceover: 'Sale fino a [data] — non perderlo'. Build on Apr urgency learnings.",
    "funnel": "pr_",
    "landing": "pdp",
    "naming": "pr_it_bed_video_ai_ss26sale_urgency_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "AI urgency variant is the one proven AI format to scale. Summer Sale = right moment.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-38",
    "campaign": "Summer Sale — PEAK VOLUME",
    "goLive": "01/06",
    "deadline": "25/05",
    "country": "",
    "priority": "High",
    "campaignType": "Peak Volume",
    "assetName": "Summer Sale — static rm_ v1 (beds bestsellers)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Product hero + % discount prominent. HP landing. Always the highest volume asset.",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_ss26sale_offer_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "WS static rm_ drove 2,230 results at CPR €5.09 — the backbone of every sale.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-39",
    "campaign": "Summer Sale — PEAK VOLUME",
    "goLive": "01/06",
    "deadline": "25/05",
    "country": "",
    "priority": "High",
    "campaignType": "Peak Volume",
    "assetName": "Summer Sale — static rm_ v2 (free embroidery)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Embroidery close-up + 'Ricamo gratuito su tutta la collezione estiva'.",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bed_static_brand_ss26sale_embroidery_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Free embroidery as offer differentiator — proven in WS essenziali CTR.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-40",
    "campaign": "Summer Sale — PEAK VOLUME",
    "goLive": "01/06",
    "deadline": "25/05",
    "country": "",
    "priority": "High",
    "campaignType": "Peak Volume",
    "assetName": "Summer Sale — static rm_ v3 (bath)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Bath products with summer offer. Separate asset — do not mix bed+bath.",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bath_static_brand_ss26sale_offer_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Bath has separate audience. Mixing bed+bath in one static confuses algorithm targeting.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-41",
    "campaign": "Summer Sale — PEAK VOLUME",
    "goLive": "01/06",
    "deadline": "25/05",
    "country": "",
    "priority": "High",
    "campaignType": "Peak Volume",
    "assetName": "Summer Sale — static rt_ (retargeting PDP specific)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Exact product user viewed + price + offer. Maximum specificity. No lifestyle.",
    "funnel": "rt_",
    "landing": "pdp",
    "naming": "rt_it_bed_static_brand_ss26sale_product_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Retargeting static rt_ PDP CPR €1.62–€1.79 in Q1. Most efficient static combo.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-42",
    "campaign": "Summer Sale — PEAK VOLUME",
    "goLive": "01/06",
    "deadline": "25/05",
    "country": "",
    "priority": "High",
    "campaignType": "Peak Volume",
    "assetName": "Summer Sale — duvet static rt_ (product specific)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Copripiumino hero + price drop + urgency copy. PDP landing.",
    "funnel": "rt_",
    "landing": "pdp",
    "naming": "rt_it_duvet_static_brand_ss26sale_product_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Duvet rt_ reshuffle CPR €2.15 in Q1. Copripiumino is the main conversion driver.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-43",
    "campaign": "Summer Sale — PEAK VOLUME",
    "goLive": "01/06",
    "deadline": "25/05",
    "country": "",
    "priority": "High",
    "campaignType": "Peak Volume",
    "assetName": "Summer Sale — carousel bestsellers rm_",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Top 6 bestsellers with prices. Final card: 'Scopri tutto il sale'. HP landing.",
    "funnel": "rm_",
    "landing": "hp",
    "naming": "rm_it_bed_carousel_brand_ss26sale_bestseller_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Carousel rm_ HP CPR €6.02 in Q1 WS. Run alongside static, not instead of.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-44",
    "campaign": "Summer Sale — PEAK VOLUME",
    "goLive": "01/06",
    "deadline": "25/05",
    "country": "",
    "priority": "High",
    "campaignType": "Peak Volume",
    "assetName": "Summer Sale — carousel rt_ (warm audience)",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Products the user browsed + related items. Strong FOMO copy on each card.",
    "funnel": "rt_",
    "landing": "hp",
    "naming": "rt_it_bed_carousel_brand_ss26sale_product_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Carousel rt_ WS HP CPR €1.43 — best carousel of Q1. Only €107 spent. Scale in Summer Sale.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-45",
    "campaign": "Summer Sale — PEAK VOLUME",
    "goLive": "01/06",
    "deadline": "25/05",
    "country": "",
    "priority": "High",
    "campaignType": "Peak Volume",
    "assetName": "Summer Sale — GIF FOMO retargeting (beds)",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Countdown or 'Sale in corso' animated loop. Rotate every 5 days to avoid fatigue.",
    "funnel": "rt_",
    "landing": "pdp",
    "naming": "rt_it_bed_gif_brand_ss26sale_fomo_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "GIF CPM €6.30–€7.06 vs €9.41 video in March. Cheapest retargeting impression.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-46",
    "campaign": "Summer Sale — PEAK VOLUME",
    "goLive": "01/06",
    "deadline": "25/05",
    "country": "",
    "priority": "High",
    "campaignType": "Peak Volume",
    "assetName": "Summer Sale — unboxing DCA refresh",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "",
    "productCluster": "",
    "hook": "New unboxing talent/angle — fresh face. Same DCA structure but summer packaging context.",
    "funnel": "rm_ + rt_",
    "landing": "plp",
    "naming": "rm_it_bed_video_ugc_ss26sale_unboxing_v1_plp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "WS unboxing DCA: 3,331 results at CPR €2.82. Highest-volume converter. Refresh for summer.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-47",
    "campaign": "Percale Capsule + Neuraé Collab",
    "goLive": "11/06",
    "deadline": "05/06",
    "country": "",
    "priority": "High",
    "campaignType": "Collab",
    "assetName": "Percale limited pattern — UGC texture video",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "",
    "productCluster": "",
    "hook": "First 2s: hand on pattern, texture feel. 'Edizione limitata' overlay. Luxury tone.",
    "funnel": "pr_",
    "landing": "pdp",
    "naming": "pr_it_bed_video_ugc_ss26percalecapsule_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Limited edition needs scarcity hook + UGC authenticity. Same formula as Botanica UGC (VR 14.7%).",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-48",
    "campaign": "Percale Capsule + Neuraé Collab",
    "goLive": "11/06",
    "deadline": "05/06",
    "country": "",
    "priority": "High",
    "campaignType": "Collab",
    "assetName": "Neuraé Collab — static announcement",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Clean collab branding: both logos + Aria colourway product. Premium positioning, no discount.",
    "funnel": "pr_",
    "landing": "hp",
    "naming": "pr_it_bed_static_brand_ss26neuraecollab_product_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Collab moments drive higher AOV + new audience reach. Static announcement = fastest to launch.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-49",
    "campaign": "Percale Capsule + Neuraé Collab",
    "goLive": "11/06",
    "deadline": "05/06",
    "country": "",
    "priority": "Medium",
    "campaignType": "Collab",
    "assetName": "Percale + Neuraé — GIF retargeting",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "",
    "productCluster": "",
    "hook": "Aria colour reveal animation. Loop 2–3s. Subtle luxury feel.",
    "funnel": "rt_",
    "landing": "pdp",
    "naming": "rt_it_bed_gif_brand_ss26percalecapsule_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "GIF on collab: fast to produce, low CPM, builds retargeting pool for new launch audience.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-50",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Percalle Botanica — UGC texture (Malva+Salvia)",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Hand on fabric, texture in first 2s. Salvia + Malva. Natural light, no studio.",
    "funnel": "pr_ + rm_",
    "landing": "HP/PDP",
    "naming": "pr_it_bed_video_ugc_ss26botanica_texture_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "UGC Botanica is best asset in account: CPR €2.85 on 177 results, CPM €6.99 vs brand €9-14.",
    "storytelling": "pr_: \"Botanica è arrivata — e in Summer Sale\"\nrm_: \"La tua collezione preferita, ora in sconto\"",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-51",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Percalle Aria — UGC texture hook",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Close-up Aria colour. Light, suspended feel. First 2s: fabric movement + colourway.",
    "funnel": "pr_",
    "landing": "PDP",
    "naming": "pr_it_bed_video_ugc_ss26aria_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Aria launched 14 May: €1.5K/day in 4 days. First time in promo — hero launch asset.",
    "storytelling": "pr_: \"Aria: la nuova tinta Percalle ora in Summer Sale\"\nrm_: \"Aria è qui — scoprila in sconto\"",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-52",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Percalle Botanica — Static ambient v1 (Malva)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Malva product in warm summer context. Ambient light. Offer % prominent.",
    "funnel": "rm_",
    "landing": "HP",
    "naming": "rm_it_bed_static_brand_ss26botanica_offer_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Static is conversion backbone. Min 2 variants per collection always.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-53",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Percalle Botanica — Static ambient v2 (Salvia)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Salvia product, natural greens. Summer mood. Same offer structure as v1.",
    "funnel": "rm_",
    "landing": "HP",
    "naming": "rm_it_bed_static_brand_ss26botanica_offer_v2_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Second variant gives algorithm options, reduces fatigue.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-54",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Percalle stagionali — GIF colori loop (Botanica+Cielo+Aria)",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Animated colour reveal: Malva → Cielo → Aria. 2-3 sec loop. No text needed.",
    "funnel": "rt_",
    "landing": "PDP",
    "naming": "rt_it_bed_gif_brand_ss26percalle_colori_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "GIF CPM €5.80 — lowest in account. Mandatory rt_ asset per active collection.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-55",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Percalle — Hero \"Freschezza\" static (temperatura angle)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "\"Caldo in arrivo. Percalle fresco, già a casa tua.\" Fabric + summer temperature hook.",
    "funnel": "pr_",
    "landing": "HP",
    "naming": "pr_it_bed_static_brand_ss26percalle_freschezza_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Unique angle: no competitor does this explicitly. Proven from DD warm-up. Problem/solution format.",
    "storytelling": "pr_: \"Caldo in arrivo. Percalle fresco, già a casa tua.\"\nalt: \"Dormire senza sudare — la promessa del Percalle\"",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-56",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Percalle — Hero \"Freschezza\" GIF (temperature loop)",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Animated: thermometer rising + fabric shot. \"Percalle fresco per le notti calde.\"",
    "funnel": "pr_ + rm_",
    "landing": "HP",
    "naming": "pr_it_bed_gif_brand_ss26percalle_freschezza_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "GIF on pr_ freschezza angle: test if temperature hook outperforms standard sale framing.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-57",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Percalle Cielo/Righe Cielo — Static ambient v1",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Azzurro cielo in summer light. Open window context. Offer visible.",
    "funnel": "rm_",
    "landing": "HP",
    "naming": "rm_it_bed_static_brand_ss26cielo_offer_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Cielo was €21.4K in SS25 (3rd colour). BIS video VR 78.9% — warm audience exists.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-58",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Percalle Cielo — GIF retargeting",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Cielo fabric loop. Sky blue dominant. 2-3s. No text.",
    "funnel": "rt_",
    "landing": "PDP",
    "naming": "rt_it_bed_gif_brand_ss26cielo_product_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "GIF rt_ CPR €11 vs rm_ CPR €101 — always retargeting, never broad rm_.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-59",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Bagno Nido d'ape — Static (audience build)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Bagno N.d'ape",
    "productCluster": "",
    "hook": "Waffle texture in summer context. Salvia/Crema colourway. Not conversion push — audience build.",
    "funnel": "pr_",
    "landing": "HP",
    "naming": "pr_it_bath_static_brand_ss26niodape_lifestyle_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Bagno N.d'ape peak is W32-W33 (Ferragosto). Build audience in Fase 1, convert in peak.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-60",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Bagno Nido d'ape — GIF texture loop",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Bagno N.d'ape",
    "productCluster": "",
    "hook": "Waffle weave close-up loop. Slow motion. 2-3s. Salvia/Crema.",
    "funnel": "rt_",
    "landing": "PDP",
    "naming": "rt_it_bath_gif_brand_ss26niodape_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "GIF mandatory per collection. Bagno N.d'ape has no GIF yet — gap to close.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-61",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Memory Foam — UGC video (lancio 18 Giu)",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Memory Foam",
    "productCluster": "",
    "hook": "First-person morning routine. \"Dormire meglio d'estate.\" Comfort + breathability hook.",
    "funnel": "pr_ + rm_ + rt_",
    "landing": "PDP",
    "naming": "pr_it_bed_video_ugc_ss26memory_comfort_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "BIS template at launch: pr_+rm_+rt_ simultaneous. Memory Foam is Fase 1 hero.",
    "storytelling": "pr_: \"Il cuscino che cambia le tue notti estive — ora in Summer Sale\"\nrm_: \"Il tuo Memory Foam è qui, ora in sconto\"",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-62",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Memory Foam — Static (BIS launch)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Memory Foam",
    "productCluster": "",
    "hook": "Product hero + \"Nuovo lancio · Summer Sale\" badge. Clean shot.",
    "funnel": "rm_ + rt_",
    "landing": "HP/PDP",
    "naming": "rm_it_bed_static_brand_ss26memory_offer_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Static is volume driver alongside UGC. BIS template needs both.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-63",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Memory Foam — GIF product loop",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Memory Foam",
    "productCluster": "",
    "hook": "Product reveal animation. \"Nuovo in estate.\" Short loop 2-3s.",
    "funnel": "rt_",
    "landing": "PDP",
    "naming": "rt_it_bed_gif_brand_ss26memory_product_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "GIF per collection mandatory. Lowest CPM format.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-64",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Beach Towels Brezza — Static v1 (context)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Beach Towels",
    "productCluster": "",
    "hook": "Portofino/sea context lifestyle. Natural light. Product + colour names.",
    "funnel": "rm_",
    "landing": "HP",
    "naming": "rm_it_bath_static_brand_ss26beach_context_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Summer products need context (sea/pool/outdoor) — not white background.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-65",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Beach Towels Brezza — GIF texture loop (sea breeze)",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Beach Towels",
    "productCluster": "",
    "hook": "Fabric in sea breeze / slow motion wave. Loop 2-3s.",
    "funnel": "rt_",
    "landing": "PDP",
    "naming": "rt_it_bath_gif_brand_ss26beach_texture_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "GIF mandatory per launch. Outdoor products need movement.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-66",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Prodotti Igienici — \"Completa la tua notte\" Static",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Igienici/Coprimaterasso",
    "productCluster": "",
    "hook": "\"Hai un Completo Lenzuola — proteggi il tuo investimento.\" Coprimaterasso + Copriguanciale.",
    "funnel": "rm_",
    "landing": "PDP",
    "naming": "rm_it_bed_static_brand_ss26igienici_crosssell_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "11K letto-baskets YTD: 97% miss Coprimaterasso. AOV +50% when in basket (€188 vs €125). First time in promo.",
    "storytelling": "rm_: \"Completa il tuo letto — proteggi ciò che ami\"\nrt_: \"Il tuo completo è perfetto. Manca solo questo.\"",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-67",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Igienici — Carousel cross-sell (Coprimaterasso + Copriguanciale)",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Igienici/Coprimaterasso",
    "productCluster": "",
    "hook": "Two-slide: Coprimaterasso + Copriguanciale. \"Completa il letto.\" Price visible.",
    "funnel": "rm_",
    "landing": "HP",
    "naming": "rm_it_bed_carousel_brand_ss26igienici_set_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Carousel on rm_ warm audience: right format for product pairing discovery.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-68",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Pre-launch Soft",
    "assetName": "Copriletto Nido d'ape — Static (retention)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Copriletto",
    "productCluster": "",
    "hook": "\"Completa il tuo letto prima dell'estate.\" Light bedspread summer hook.",
    "funnel": "rm_",
    "landing": "HP",
    "naming": "rm_it_bed_static_brand_ss26copriletto_offer_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Copriletto push only Weeks 1-3 SS. Demand drops >25°C — stop before Ferragosto.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-69",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "Medium",
    "campaignType": "Pre-launch Soft",
    "assetName": "SS26 Urgency launch — GIF \"Summer Sale è qui\"",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Mixed",
    "productCluster": "",
    "hook": "Animated: \"Summer Sale · sconti fino al -25%\". Deploy Day 1 ADS ON (3 luglio).",
    "funnel": "rm_ + rt_",
    "landing": "HP",
    "naming": "rm_it_mixed_gif_brand_ss26launch_urgency_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "First urgency asset. GIF CPM cheapest format for FOMO messaging.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-70",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "Medium",
    "campaignType": "Pre-launch Soft",
    "assetName": "SS26 Urgency launch — Static offer banner v1",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Mixed",
    "productCluster": "",
    "hook": "\"Summer Sale · qualità che ami in sconto\" HP. % offer prominent. WS26 graphic identity.",
    "funnel": "rm_",
    "landing": "HP",
    "naming": "rm_it_mixed_static_brand_ss26launch_offer_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "WS26 static rm_ CPR €3.26–€5.09 — the conversion workhorse. Replicate format.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-71",
    "campaign": "SS26 — Pre-lancio Batch",
    "goLive": "26/06",
    "deadline": "25/06/2026",
    "country": "ITA",
    "priority": "Medium",
    "campaignType": "Pre-launch Soft",
    "assetName": "Catalog DCA template — RM Engagers (feed SS)",
    "format": "Carousel",
    "creativeType": "Brand (DCA)",
    "productCategory": "Mixed",
    "productCluster": "",
    "hook": "Dynamic feed carousel. Top products in SS. Rotate weekly.",
    "funnel": "rm_",
    "landing": "PLP",
    "naming": "rm_it_mixed_carousel_dca_ss26catalog_v1_plp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Always-on DCA: best CPM in account (€4.91 Q1). Never turn off. Refresh feed weekly.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-72",
    "campaign": "Neuraé Collab — Aria (lancio 16 Giu)",
    "goLive": "16/06",
    "deadline": "12/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Collab",
    "assetName": "Neuraé Collab — Static announcement (Aria)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "\"Beauty Sleep by Neuraé x Dalfilo.\" Both logos + Aria product. No discount messaging.",
    "funnel": "pr_ + rm_",
    "landing": "HP",
    "naming": "pr_it_bed_static_brand_ss26neuraecollab_aria_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Collab moments drive higher AOV + new audience reach. Static = fastest to launch.",
    "storytelling": "pr_: \"Neuraé x Dalfilo — la notte del benessere\"\nrm_: \"Aria by Dalfilo × Neuraé — disponibile ora\"",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-73",
    "campaign": "Neuraé Collab — Aria (lancio 16 Giu)",
    "goLive": "16/06",
    "deadline": "12/06/2026",
    "country": "ITA",
    "priority": "Medium",
    "campaignType": "Collab",
    "assetName": "Neuraé Collab — GIF Aria colour reveal",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Aria colour reveal animation. Subtle luxury feel. Loop 2-3s.",
    "funnel": "rt_",
    "landing": "PDP",
    "naming": "rt_it_bed_gif_brand_ss26neuraecollab_aria_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "GIF on collab: fast to produce, low CPM, builds retargeting pool for new launch audience.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-74",
    "campaign": "SS26 — W29 Free Embroidery PEAK",
    "goLive": "03/07",
    "deadline": "05/07/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Peak Push",
    "assetName": "Free Embroidery — UGC video (ricamo + Percalle stagionali)",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Close-up embroidery stitching in first 2s. Emotional personal touch. Gift angle.",
    "funnel": "pr_ + rm_",
    "landing": "PDP",
    "naming": "pr_it_bed_video_ugc_ss26freembroidery_ricamo_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Free Embroidery was +39% vs SS25 average in W29. This is the biggest lever of the season.",
    "storytelling": "pr_: \"Percalle stagionali con ricamo gratuito — solo questa settimana\"\nrm_: \"Il tuo regalo personalizzato — Free Embroidery è tornato\"",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-75",
    "campaign": "SS26 — W29 Free Embroidery PEAK",
    "goLive": "03/07",
    "deadline": "05/07/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Peak Push",
    "assetName": "Free Embroidery — GIF countdown timer (ricamo)",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Mixed",
    "productCluster": "",
    "hook": "\"Ricamo gratuito · ultimi giorni\" countdown animation. No static background.",
    "funnel": "rt_ + rm_",
    "landing": "PDP",
    "naming": "rt_it_bed_gif_brand_ss26freembroidery_countdown_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "GIF countdown: lowest CPM format + FOMO urgency. Proven Mamma formula (CPM €4.21).",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-76",
    "campaign": "SS26 — W29 Free Embroidery PEAK",
    "goLive": "03/07",
    "deadline": "05/07/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Peak Push",
    "assetName": "Free Embroidery — Static PDP overlay (stagionali)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Product + embroidery close-up. \"Ricamo gratuito su Botanica, Cielo, Aria.\" PDP specific.",
    "funnel": "rm_ + rt_",
    "landing": "PDP",
    "naming": "rm_it_bed_static_brand_ss26freembroidery_pdp_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Dedicated PDP static for embroidery: proven conversion asset in Mamma campaign.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-77",
    "campaign": "SS26 — W29 Free Embroidery PEAK",
    "goLive": "03/07",
    "deadline": "05/07/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Peak Push",
    "assetName": "Free Embroidery — UGC+AI urgenza+ASMR (Percalle)",
    "format": "Video",
    "creativeType": "UGC+AI",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Same clip as UGC v1. Urgency+ASMR voiceover: \"Ricamo gratuito solo questa settimana — non aspettare.\"",
    "funnel": "pr_",
    "landing": "PDP",
    "naming": "pr_it_bed_video_ai_ss26freembroidery_urgenza_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "AI ASMR+Urgenza CPR €14.83 vs ASMR-only €41. Best AI variant validated. Use only this combination.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-78",
    "campaign": "SS26 — W31 Last Chance Transition",
    "goLive": "29/07",
    "deadline": "22/07/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Last Chance",
    "assetName": "Last Chance — Hero Percalle \"ultimi pezzi\" (Botanica)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "\"Botanica · ultimi pezzi disponibili\" scarcity. Same product, new urgency narrative.",
    "funnel": "rm_ + rt_",
    "landing": "HP/PDP",
    "naming": "rm_it_bed_static_brand_ss26lc_percalle_scarc_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Phase 2: scarcity per colour is more urgent than \"sale continues\". Botanica first (highest demand).",
    "storytelling": "rm_: \"Ultimi Botanica disponibili — Last Chance Summer Sale\"\nrt_: \"Botanica · soli pochi pezzi\"",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-79",
    "campaign": "SS26 — W31 Last Chance Transition",
    "goLive": "29/07",
    "deadline": "22/07/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Last Chance",
    "assetName": "Last Chance — GIF countdown \"ultimi giorni\"",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Mixed",
    "productCluster": "",
    "hook": "\"Summer Sale · ultimi giorni\" countdown. Reshuffle visual from Fase 1.",
    "funnel": "rt_ + rm_",
    "landing": "PDP",
    "naming": "rt_it_mixed_gif_brand_ss26lc_countdown_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "GIF countdown is cheapest urgency format. Rotate every 5 days to avoid fatigue.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-80",
    "campaign": "SS26 — W31 Last Chance Transition",
    "goLive": "29/07",
    "deadline": "22/07/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Last Chance",
    "assetName": "Last Chance — Percalle Cielo \"ultimi pezzi\"",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "\"Cielo · ultimi pezzi\" scarcity. Specific colour urgency.",
    "funnel": "rt_",
    "landing": "PDP",
    "naming": "rt_it_bed_static_brand_ss26lc_cielo_scarc_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Scarcity per colour: more conversion power than generic \"last chance\".",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-81",
    "campaign": "SS26 — W33 Ferragosto + Ricamo",
    "goLive": "03/07",
    "deadline": "05/08/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Peak Push",
    "assetName": "Bagno Nido d'ape — UGC video (peak storico Ferragosto)",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Bagno N.d'ape",
    "productCluster": "",
    "hook": "Post-shower waffle texture moment. \"Freschezza dopo la doccia.\" Summer morning routine.",
    "funnel": "pr_ + rm_",
    "landing": "HP",
    "naming": "pr_it_bath_video_ugc_ss26niodape_freschezza_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Historical peak spugna W32-W33 (Ferragosto). UGC must be produced before July launch.",
    "storytelling": "pr_: \"La freschezza dopo la doccia — Nido d'ape Dalfilo\"\nrm_: \"Il bagno che ami — ora in sconto Last Chance\"",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-82",
    "campaign": "SS26 — W33 Ferragosto + Ricamo",
    "goLive": "03/07",
    "deadline": "05/08/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Peak Push",
    "assetName": "Ferragosto + Free Embroidery — GIF countdown (Nido d'ape + Ricamo)",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Mixed",
    "productCluster": "",
    "hook": "\"Ferragosto · Ricamo gratuito\" double hook animation.",
    "funnel": "rt_ + rm_",
    "landing": "PDP",
    "naming": "rt_it_mixed_gif_brand_ss26ferragosto_countdown_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "W33 SS25 made €128K — Ferragosto + Free Embroidery combination is proven peak driver.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-83",
    "campaign": "SS26 — W33 Ferragosto + Ricamo",
    "goLive": "03/07",
    "deadline": "05/08/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Peak Push",
    "assetName": "W33 — UGC+AI urgenza+ASMR \"Ferragosto last chance\"",
    "format": "Video",
    "creativeType": "UGC+AI",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Urgency voiceover: \"Ferragosto è qui — ultimi giorni di Summer Sale con ricamo gratuito.\"",
    "funnel": "pr_ + rm_",
    "landing": "HP",
    "naming": "pr_it_bed_video_ai_ss26ferragosto_urgenza_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "AI ASMR+Urgenza only valid variant (CPR €14.83). Peak week = right moment to scale.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-84",
    "campaign": "SS26 — W34 Copriletto + Kids",
    "goLive": "17/08",
    "deadline": "16/08/2026",
    "country": "ITA",
    "priority": "Medium",
    "campaignType": "Last Chance",
    "assetName": "Copriletto — Static peak agosto (Cotone/Mussola)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Copriletto",
    "productCluster": "",
    "hook": "\"Preparati per l'autunno — Copriletto Last Chance.\" Cooler tone.",
    "funnel": "rm_ + rt_",
    "landing": "HP/PDP",
    "naming": "rm_it_bed_static_brand_ss26copriletto_agosto_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Historical August peak for Copriletto. Mussola ~400 extra units incoming. Run W34 only.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-85",
    "campaign": "SS26 — W34 Copriletto + Kids",
    "goLive": "17/08",
    "deadline": "16/08/2026",
    "country": "ITA",
    "priority": "Medium",
    "campaignType": "Last Chance",
    "assetName": "Kids — UGC video soft launch (bambino autentico)",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Kids Collection",
    "productCluster": "",
    "hook": "Real child reaction. First 2s: child + product. No staged lifestyle. Authentic.",
    "funnel": "pr_ + rm_",
    "landing": "HP",
    "naming": "pr_it_bed_video_ugc_ss26kids_authentic_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Kids launched 7 May at €680/day. Carousel CPR €11-12. UGC video is the missing cold-audience layer.",
    "storytelling": "pr_: \"La linea bambini che stavi aspettando — Summer Sale\"\nrm_: \"La camera dei tuoi bambini in sconto\"",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-86",
    "campaign": "SS26 — W35 Final Urgency PEAK",
    "goLive": "24/08",
    "deadline": "17/08/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Final Push",
    "assetName": "Final Urgency — UGC+AI \"Ultima Chiamata\" cross-categoria",
    "format": "Video",
    "creativeType": "UGC+AI",
    "productCategory": "Mixed",
    "productCluster": "",
    "hook": "Urgency voiceover: \"Summer Sale termina domenica — ultimi pezzi, ultime ore.\"",
    "funnel": "pr_ + rm_",
    "landing": "HP",
    "naming": "pr_it_mixed_video_ai_ss26finalurgency_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "W35 SS25 made €142K. AI ASMR+Urgenza is the format. Cross-categoria: beds + bath.",
    "storytelling": "pr_: \"Ultima chiamata | Summer Sale termina domenica\"\nrm_: \"Ultimi pezzi — non aspettare\"",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-87",
    "campaign": "SS26 — W35 Final Urgency PEAK",
    "goLive": "24/08",
    "deadline": "17/08/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Final Push",
    "assetName": "Final Urgency — GIF timer countdown 24h",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Mixed",
    "productCluster": "",
    "hook": "\"Summer Sale termina tra [X] ore\" animated countdown. Cross-category.",
    "funnel": "rt_ + rm_",
    "landing": "PDP/HP",
    "naming": "rt_it_mixed_gif_brand_ss26finalurgency_timer_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Final urgency GIF: cheapest impression in last days. Rotate versions every 48h.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-88",
    "campaign": "SS26 — W35 Final Urgency PEAK",
    "goLive": "24/08",
    "deadline": "17/08/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Final Push",
    "assetName": "Final Urgency — Static \"Ultima Chiamata\" Percalle scarcity",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "\"Ultimi stagionali · Summer Sale termina domenica.\" Botanica/Cielo scarcity.",
    "funnel": "rm_ + rt_",
    "landing": "HP",
    "naming": "rm_it_bed_static_brand_ss26finalurgency_percalle_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Percalle must appear in final urgency: it is 48% of budget and audience is maximum.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-89",
    "campaign": "SS26 — W35 Final Urgency PEAK",
    "goLive": "24/08",
    "deadline": "17/08/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Final Push",
    "assetName": "Final Urgency — Static \"Ultima Chiamata\" Bagno N.d'ape",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Bagno N.d'ape",
    "productCluster": "",
    "hook": "\"Nido d'ape · ultimi pezzi estate.\" Bath separately from bed.",
    "funnel": "rm_ + rt_",
    "landing": "HP",
    "naming": "rm_it_bath_static_brand_ss26finalurgency_niodape_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Bath has separate audience. Separate asset from bed in final push.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-90",
    "campaign": "SS26 — W35 Final Urgency PEAK",
    "goLive": "24/08",
    "deadline": "17/08/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Final Push",
    "assetName": "Final Urgency — Carousel \"ultimi pezzi\" warm audience",
    "format": "Carousel",
    "creativeType": "Brand",
    "productCategory": "Mixed",
    "productCluster": "",
    "hook": "Products user browsed + \"ultimi pezzi\". Strong FOMO each card. Warm only.",
    "funnel": "rt_",
    "landing": "HP",
    "naming": "rt_it_mixed_carousel_brand_ss26finalurgency_scarc_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Carousel rt_ WS HP CPR €1.43 — best carousel Q1. Only on warm audience. Scale in Final Urgency.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-91",
    "campaign": "Sport Collection — Funnel Opening",
    "goLive": "19/05",
    "deadline": "15/05/2026",
    "country": "All markets",
    "priority": "High",
    "campaignType": "Product Launch",
    "assetName": "Sport — UGC video (movimento hook, first-person)",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Sport",
    "productCluster": "",
    "hook": "First 2s: physical movement (gym, morning, travel). First-person POV. Real use. No studio.",
    "funnel": "pr_",
    "landing": "HP",
    "naming": "pr_it_bath_video_ugc_ss26sport_movement_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "rt_ static CPR €3.44 on 141 results — warm audience exists. UGC is the missing prospecting layer. CPR deteriorated €2.27→€11 from pool exhaustion.",
    "storytelling": "pr_: \"Qualità per chi non si ferma — linea Sport Dalfilo\"\nrm_: \"Lo sport che ami, il comfort che meriti\"",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-92",
    "campaign": "Sport Collection — Funnel Opening",
    "goLive": "19/05",
    "deadline": "15/05/2026",
    "country": "All markets",
    "priority": "Medium",
    "campaignType": "Product Launch",
    "assetName": "Sport — UGC+AI voiceover (performance angle)",
    "format": "Video",
    "creativeType": "UGC+AI",
    "productCategory": "Sport",
    "productCluster": "",
    "hook": "Same clip as UGC v1. AI voiceover: \"Qualità per chi si allena.\" Performance/quality angle.",
    "funnel": "pr_",
    "landing": "HP",
    "naming": "pr_it_bath_video_ai_ss26sport_performance_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "A/B test vs UGC without voice. Continue testing on Sport after Botanica learnings. ASMR+Urgenza only.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-93",
    "campaign": "Sport Collection — Funnel Opening",
    "goLive": "19/05",
    "deadline": "15/05/2026",
    "country": "All markets",
    "priority": "High",
    "campaignType": "Product Launch",
    "assetName": "Sport — GIF retargeting (product in motion)",
    "format": "GIF",
    "creativeType": "Brand",
    "productCategory": "Sport",
    "productCluster": "",
    "hook": "Product in motion. Short loop 2-3s. No text — product speaks.",
    "funnel": "rt_",
    "landing": "PDP",
    "naming": "rt_it_bath_gif_brand_ss26sport_product_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Sport has no GIF yet. GIF CPM €5.80 average — cheapest format for warm rt_ audience.",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-94",
    "campaign": "Sport Collection — Funnel Opening",
    "goLive": "19/05",
    "deadline": "15/05/2026",
    "country": "ITA",
    "priority": "Medium",
    "campaignType": "Product Launch",
    "assetName": "Sport — Static prospecting (pr_)",
    "format": "Static",
    "creativeType": "Brand",
    "productCategory": "Sport",
    "productCluster": "",
    "hook": "Accappatoio Sport hero. Clean product + lifestyle hook. \"Qualità per ogni momento.\"",
    "funnel": "pr_",
    "landing": "HP",
    "naming": "pr_it_bath_static_brand_ss26sport_lifestyle_v1_hp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "pr_ static needed to fill the pool — rt_ alone exhausts the audience (CPR went €2.27→€11).",
    "storytelling": "",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-95",
    "campaign": "Percalle — UGC Freschezza hero",
    "goLive": "26/06",
    "deadline": "20/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Core Campaign",
    "assetName": "Percalle Botanica — UGC freschezza texture (outdoor)",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Hand on Salvia fabric. Cool texture feel. Outdoor natural light. \"Fresco anche di notte.\"",
    "funnel": "pr_",
    "landing": "PDP",
    "naming": "pr_it_bed_video_ugc_ss26percalle_freschezza_v2_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Temperature hook + UGC = most original SS26 asset. No competitor does this explicitly.",
    "storytelling": "pr_: \"Fresco anche di notte — Percalle Salvia\"\nalt: \"Il tessuto che respira per le notti di luglio\"",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  },
  {
    "id": "asset-96",
    "campaign": "Percalle — UGC Freschezza hero",
    "goLive": "26/06",
    "deadline": "20/06/2026",
    "country": "ITA",
    "priority": "High",
    "campaignType": "Core Campaign",
    "assetName": "Percalle Aria — UGC new launch + freschezza angle",
    "format": "Video",
    "creativeType": "UGC",
    "productCategory": "Percalle",
    "productCluster": "",
    "hook": "Aria colourway reveal with summer light. \"Aria: il nome dice tutto.\" Cool, light feel.",
    "funnel": "pr_",
    "landing": "PDP",
    "naming": "pr_it_bed_video_ugc_ss26aria_freschezza_v1_pdp",
    "assignee": "Federica",
    "status": "Draft",
    "rationale": "Aria has no UGC yet — only static. UGC needed for cold audience prospecting (CPM gap €6.99 vs €9-14).",
    "storytelling": "pr_: \"Aria: il nuovo Percalle che respira\"\nrm_: \"Hai visto Aria? Ora in Summer Sale\"",
    "notes": "",
    "cta": "",
    "prospectingMessage": "",
    "remarketingMessage": "",
    "performance": null,
    "visual": "",
    "visualName": ""
  }
];
